"This is completed mapping template."


mapping_template_name = [
    {'id': '93059', 'name': 'Żele', 'parent': 'Kąpiel i prysznic', 'wszystko_id': '13973', 'wszystko_name': 'Żele'},
    {'id': '93067', 'name': 'Acetony, removery', 'parent': 'Zmywacze, odtłuszczacze, kleje', 'wszystko_id': '13938', 'Acetony, removery': 'str'},
    {'id': '47631', 'name': 'Koloryzacja', 'parent': 'Włosy', 'wszystko_id': '14102', 'wszystko_name': 'str'},
    {'id': '93072', 'name': 'Kleje', 'parent': 'Przedłużanie rzęs, sztuczne rzęsy', 'wszystko_id': '13849', 'wszystko_name': 'str'},
    {'id': '261010', 'name': 'Cykady', 'parent': 'Sztuczne', 'wszystko_id': '12080', 'wszystko_name': 'str'},
    {'id': '93074', 'name': 'Rzęsy', 'parent': 'Przedłużanie rzęs, sztuczne rzęsy', 'wszystko_id': '13852', 'wszystko_name': 'str'},
    {'id': '10774', 'name': 'Źródła światła', 'parent': 'Oświetlenie', 'wszystko_id': '1109', 'wszystko_name': 'str'},
    {'id': '255638', 'name': 'Serum i odżywki do brwi i rzęs', 'parent': 'Oczy', 'wszystko_id': '13853', 'wszystko_name': 'str'},
    {'id': '93079', 'name': 'Damskie', 'parent': 'Zestawy', 'wszystko_id': '13960', 'wszystko_name': 'str'},
    {'id': '49054', 'name': 'Palety do makijażu i zestawy', 'parent': 'Makijaż', 'wszystko_id': '13855', 'wszystko_name': 'str'},
    {'id': '315687', 'name': 'Zestawy do makijażu ust', 'parent': 'Usta', 'wszystko_id': '13879', 'wszystko_name': 'str'},
    {'id': '317736', 'name': 'Pęsety', 'parent': 'Akcesoria', 'wszystko_id': '14190', 'wszystko_name': 'str'},
    {'id': '121776', 'name': 'Woblery', 'parent': 'Sztuczne', 'wszystko_id': '13135', 'wszystko_name': 'str'},
    {'id': '317745', 'name': 'Temperówki', 'parent': 'Akcesoria', 'wszystko_id': '13840', 'wszystko_name': 'str'},
    {'id': '89009', 'name': 'Pędzle do makijażu', 'parent': 'Pędzle i akcesoria', 'wszystko_id': '13859', 'wszystko_name': 'str'},
    {'id': '89011', 'name': 'Korektory', 'parent': 'Twarz', 'wszystko_id': '13865', 'wszystko_name': 'str'},
    {'id': '317748', 'name': 'Zalotki', 'parent': 'Akcesoria', 'wszystko_id': '13841', 'wszystko_name': 'str'},
    {'id': '308917', 'name': 'Separatory do pedicure', 'parent': 'Akcesoria i przybory', 'wszystko_id': '13894', 'wszystko_name': 'str'},
    {'id': '89012', 'name': 'Bazy pod cienie', 'parent': 'Oczy', 'wszystko_id': '13842', 'wszystko_name': 'str'},
    {'id': '89010', 'name': 'Bazy pod makijaż', 'parent': 'Twarz', 'wszystko_id': '13863', 'wszystko_name': 'str'},
    {'id': '90424', 'name': 'Do paznokci', 'parent': 'Odżywki do paznokci i skórek', 'wszystko_id': 'Do paznokci', 'wszystko_name': 'str'},
    {'id': '90426', 'name': 'Nabłyszczacze, utrwalacze', 'parent': 'Manicure i pedicure', 'wszystko_id': '13909', 'wszystko_name': 'str'},
    {'id': '90428', 'name': 'Odtłuszczacze, primery', 'parent': 'Zmywacze, odtłuszczacze, kleje', 'wszystko_id': '13940', 'wszystko_name': 'str'},
    {'id': '90430', 'name': 'Acetonowe', 'parent': 'Zmywacze', 'wszystko_id': '13936', 'wszystko_name': 'str'},
    {'id': '90431', 'name': 'Bezacetonowe', 'parent': 'Zmywacze', 'wszystko_id': '13937', 'wszystko_name': 'str'},
    {'id': '255558', 'name': 'Eyelinery', 'parent': 'Oczy', 'wszystko_id': '13844', 'wszystko_name': 'str'},
    {'id': '255559', 'name': 'Makijaż brwi', 'parent': 'Oczy', 'wszystko_id': '13847', 'wszystko_name': 'str'},
    {'id': '255560', 'name': 'Gąbki do makijażu', 'parent': 'Pędzle i akcesoria', 'wszystko_id': '13857', 'wszystko_name': 'str'},
    {'id': '256082', 'name': 'Szczoteczki do twarzy', 'parent': 'Urządzenia kosmetyczne', 'wszystko_id': '14093', 'wszystko_name': 'str'},
    {'id': '255956', 'name': 'Bronzery', 'parent': 'Twarz', 'wszystko_id': '13864', 'wszystko_name': 'str'},
    {'id': '255957', 'name': 'Rozświetlacze', 'parent': 'Twarz', 'wszystko_id': '13870', 'wszystko_name': 'str'},
    {'id': '255958', 'name': 'Kremy koloryzujące', 'parent': 'Twarz', 'wszystko_id': '14239', 'wszystko_name': 'str'},
    {'id': '17752', 'name': 'Perfumy i wody perfumowane', 'parent': 'Zapachy dla kobiet', 'wszystko_id': '13946', 'wszystko_name': 'str'},
    {'id': '17753', 'name': 'Wody toaletowe', 'parent': 'Zapachy dla kobiet', 'wszystko_id': '13948', 'wszystko_name': 'str'},
    {'id': '126042', 'name': 'Lakiery hybrydowe', 'parent': 'Manicure i pedicure', 'wszystko_id': '13907', 'wszystko_name': 'str'},
    {'id': '17756', 'name': 'Wody perfumowane', 'parent': 'Zapachy dla mężczyzn', 'wszystko_id': '13952', 'wszystko_name': 'str'},
    {'id': '17757', 'name': 'Wody toaletowe', 'parent': 'Zapachy dla mężczyzn', 'wszystko_id': '13954', 'wszystko_name': 'str'},
    {'id': '45664', 'name': 'Cienie', 'parent': 'Oczy', 'wszystko_id': '13843', 'wszystko_name': 'str'},
    {'id': '45665', 'name': 'Kredki do oczu', 'parent': 'Oczy', 'wszystko_id': '13846', 'wszystko_name': 'str'},
    {'id': '45666', 'name': 'Tusze do rzęs', 'parent': 'Oczy', 'wszystko_id': '13854', 'wszystko_name': 'str'},
    {'id': '45668', 'name': 'Podkłady', 'parent': 'Twarz', 'wszystko_id': '13867', 'wszystko_name': 'str'},
    {'id': '45669', 'name': 'Pudry', 'parent': 'Twarz', 'wszystko_id': '13869', 'wszystko_name': 'str'},
    {'id': '45670', 'name': 'Róże do policzków', 'parent': 'Twarz', 'wszystko_id': '13871', 'wszystko_name': 'str'},
    {'id': '5351', 'name': 'Balsamy, masła, kremy', 'parent': 'Ciało', 'wszystko_id': '13965', 'wszystko_name': 'str'},
    {'id': '45672', 'name': 'Pielęgnacja ust', 'parent': 'Twarz', 'wszystko_id': '14083', 'wszystko_name': 'str'},
    {'id': '45673', 'name': 'Błyszczyki', 'parent': 'Usta', 'wszystko_id': '13875', 'wszystko_name': 'str'},
    {'id': '45674', 'name': 'Konturówki', 'parent': 'Usta', 'wszystko_id': '13876', 'wszystko_name': 'str'},
    {'id': '5355', 'name': 'Kremy do rąk', 'parent': 'Dłonie i stopy', 'wszystko_id': '13982', 'wszystko_name': 'str'},
    {'id': '45675', 'name': 'Pomadki', 'parent': 'Usta', 'wszystko_id': '14241', 'wszystko_name': 'str'},
    {'id': '144744', 'name': 'Olejki do włosów', 'parent': 'Włosy', 'wszystko_id': '14252', 'wszystko_name': 'str'},
    {'id': '260718', 'name': 'Pilniki, tarki, pumeksy do stóp', 'parent': 'Akcesoria i przybory', 'wszystko_id': '13890', 'wszystko_name': 'str'},
    {'id': '45680', 'name': 'Lakiery do paznokci', 'parent': 'Manicure i pedicure', 'wszystko_id': '13906', 'wszystko_name': 'str'},
    {'id': '5361', 'name': 'Oczyszczanie i demakijaż', 'parent': 'Twarz', 'wszystko_id': '14080', 'wszystko_name': 'str'},
    {'id': '45682', 'name': 'Ozdoby i przyrządy do zdobień', 'parent': 'Manicure i pedicure', 'wszystko_id': '13913', 'wszystko_name': 'str'},
    {'id': '45683', 'name': 'Podkłady, bazy', 'parent': 'Manicure i pedicure', 'wszystko_id': '13914', 'wszystko_name': 'str'},
    {'id': '5364', 'name': 'Odżywki do włosów', 'parent': 'Włosy', 'wszystko_id': '14106', 'wszystko_name': 'str'},
    {'id': '5363', 'name': 'Szampony', 'parent': 'Włosy', 'wszystko_id': '14117', 'wszystko_name': 'str'},
    {'id': '255989', 'name': 'Utrwalenie makijażu', 'parent': 'Twarz', 'wszystko_id': '13872', 'wszystko_name': 'str'},
    {'id': '45687', 'name': 'Nożyczki, cążki, kopytka', 'parent': 'Akcesoria i przybory', 'wszystko_id': '13885', 'wszystko_name': 'str'},
    {'id': '45689', 'name': 'Pilniki i polerki do rąk', 'parent': 'Akcesoria i przybory', 'wszystko_id': '13889', 'wszystko_name': 'str'},
    {'id': '12922', 'name': 'Bulwy, cebulki, kłącza', 'parent': 'Rośliny', 'wszystko_id': '1019', 'wszystko_name': 'str'},
]